# Generated by Django 4.2 on 2025-05-26 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_recordwinners_delete_bidwinners'),
        ('shop', '0012_winner_phonenumber'),
    ]

    operations = [
    ]
